print "Starting maya loading and fbx conversion \n";
			
if (`file -q -exists "/Users/Home/BodegaBash/Assets/Models/MAYA_generichar_01.ma"`)
{
	file -o "/Users/Home/BodegaBash/Assets/Models/MAYA_generichar_01.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/Home/BodegaBash/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

system ("del \"!//UNITY_TEMP_WIN//!\\CommandPipe\"");

$donepipeKill = `fopen "/Users/Home/BodegaBash/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
